name: cypress-tests
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: install dependencies
        run: npm ci

      - name: configure amplify
        uses: ambientlight/amplify-cli-action@0.3.0
        with:
          amplify_command: configure
          amplify_env: prod
          amplify_cli_version: 12.10.1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.WS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1

      - name: Write the cypress.env.json file
        run: |
          echo '${{ secrets.CYPRESS_TESTUSER_ENV }}' >> cypress.env.json

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          start: npx vite --host
          wait-on: "http://localhost:5173"
