name: cypress-tests
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: install dependencies
        run: npm ci

      - name: Write the cypress.env.json file
        run: |
          echo '${{ secrets.CYPRESS_TESTUSER_ENV }}' >> cypress.env.json

      - name: Write the aws-exports file
        run: |
          echo '${{ secrets.CYPRESS_AWS-EXPORTS }}' >> ./asw-exports

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          start: npx vite --host
          wait-on: "http://localhost:5173"
